In [49]:
import numpy as np # Linear Algebra
import pandas as pd # Data Processing, CSV file

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [50]:
# ignore warnings
import warnings

warnings.filterwarnings('ignore')

In [51]:
# Read Dataset and named as df
df = pd.read_excel(r'/home/bane/CrediSure/datasets/raw/default of credit card clients.xls'
        , engine='xlrd', header=1)
df

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,29996,220000,1,3,1,39,0,0,0,0,...,88004,31237,15980,8500,20000,5003,3047,5000,1000,0
29996,29997,150000,1,3,2,43,-1,-1,-1,-1,...,8979,5190,0,1837,3526,8998,129,0,0,0
29997,29998,30000,1,2,2,37,4,3,2,-1,...,20878,20582,19357,0,0,22000,4200,2000,3100,1
29998,29999,80000,1,3,1,41,1,-1,0,0,...,52774,11855,48944,85900,3409,1178,1926,52964,1804,1
29999,30000,50000,1,2,1,46,0,0,0,0,...,36535,32428,15313,2078,1800,1430,1000,1000,1000,1

### Additoinal Information :
Given by UCI Machine learning repository
1) Gender (1=male, 2=female)
2) Education (1=Graduate school, 2=university, 3=high school, 4=others)
3) Martial status (1=married, 2=unmarried)
4) Age is in year already
5) Default payment next month (0=unpaid, 1=paid)
6)

## Exploratary Data Analysis

In [52]:
print('Number of Rows * Columns: ', df.shape)

Number of Rows * Columns:  (30000, 25)

In [53]:
df.head()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
0,1,20000,2,2,1,24,2,2,-1,-1,...,0,0,0,0,689,0,0,0,0,1
1,2,120000,2,2,2,26,-1,2,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,3,90000,2,2,2,34,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,4,50000,2,2,1,37,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,5,50000,1,2,1,57,-1,0,-1,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [54]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   ID                          30000 non-null  int64
 1   LIMIT_BAL                   30000 non-null  int64
 2   SEX                         30000 non-null  int64
 3   EDUCATION                   30000 non-null  int64
 4   MARRIAGE                    30000 non-null  int64
 5   AGE                         30000 non-null  int64
 6   PAY_0                       30000 non-null  int64
 7   PAY_2                       30000 non-null  int64
 8   PAY_3                       30000 non-null  int64
 9   PAY_4                       30000 non-null  int64
 10  PAY_5                       30000 non-null  int64
 11  PAY_6                       30000 non-null  int64
 12  BILL_AMT1                   30000 non-null  int64
 13  BILL_AMT2                   30000 non-null  int64
 14  BILL_AMT3                   30000 non-null  int64
 15  BILL_AMT4                   30000 non-null  int64
 16  BILL_AMT5                   30000 non-null  int64
 17  BILL_AMT6                   30000 non-null  int64
 18  PAY_AMT1                    30000 non-null  int64
 19  PAY_AMT2                    30000 non-null  int64
 20  PAY_AMT3                    30000 non-null  int64
 21  PAY_AMT4                    30000 non-null  int64
 22  PAY_AMT5                    30000 non-null  int64
 23  PAY_AMT6                    30000 non-null  int64
 24  default payment next month  30000 non-null  int64
dtypes: int64(25)
memory usage: 5.7 MB

here

In [55]:
# Datatypes of each 
df.dtypes

ID                            int64
LIMIT_BAL                     int64
SEX                           int64
EDUCATION                     int64
MARRIAGE                      int64
AGE                           int64
PAY_0                         int64
PAY_2                         int64
PAY_3                         int64
PAY_4                         int64
PAY_5                         int64
PAY_6                         int64
BILL_AMT1                     int64
BILL_AMT2                     int64
BILL_AMT3                     int64
BILL_AMT4                     int64
BILL_AMT5                     int64
BILL_AMT6                     int64
PAY_AMT1                      int64
PAY_AMT2                      int64
PAY_AMT3                      int64
PAY_AMT4                      int64
PAY_AMT5                      int64
PAY_AMT6                      int64
default payment next month    int64
dtype: object

In [56]:
# Descriptive Statistics
df.describe()

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,default payment next month
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,3.000000e+04,30000.00000,30000.000000,30000.000000,30000.000000,30000.000000
mean,15000.500000,167484.322667,1.603733,1.853133,1.551867,35.485500,-0.016700,-0.133767,-0.166200,-0.220667,...,43262.948967,40311.400967,38871.760400,5663.580500,5.921163e+03,5225.68150,4826.076867,4799.387633,5215.502567,0.221200
std,8660.398374,129747.661567,0.489129,0.790349,0.521970,9.217904,1.123802,1.197186,1.196868,1.169139,...,64332.856134,60797.155770,59554.107537,16563.280354,2.304087e+04,17606.96147,15666.159744,15278.305679,17777.465775,0.415062
min,1.000000,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.00000,0.000000,0.000000,0.000000,0.000000
25%,7500.750000,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2326.750000,1763.000000,1256.000000,1000.000000,8.330000e+02,390.00000,296.000000,252.500000,117.750000,0.000000
50%,15000.500000,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,...,19052.000000,18104.500000,17071.000000,2100.000000,2.009000e+03,1800.00000,1500.000000,1500.000000,1500.000000,0.000000
75%,22500.250000,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,...,54506.000000,50190.500000,49198.250000,5006.000000,5.000000e+03,4505.00000,4013.250000,4031.500000,4000.000000,0.000000
max,30000.000000,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.00000,621000.000000,426529.000000,528666.000000,1.000000

In [57]:
print("The columns names in datasets are : ", df.columns)

The columns names in datasets are :  Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_0',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='str')

In [58]:
# Droping irreleavent attributes
df.drop(columns=['ID','SEX','MARRIAGE'], inplace=True)

In [59]:
# Rename the target variable to 'DEFAULT'
df.rename(columns={'default payment next month': 'DEFAULT '}, inplace=True)

In [60]:
print('Updated shape of dataset : ', df.shape)

Updated shape of dataset :  (30000, 22)

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 22 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  30000 non-null  int64
 1   EDUCATION  30000 non-null  int64
 2   AGE        30000 non-null  int64
 3   PAY_0      30000 non-null  int64
 4   PAY_2      30000 non-null  int64
 5   PAY_3      30000 non-null  int64
 6   PAY_4      30000 non-null  int64
 7   PAY_5      30000 non-null  int64
 8   PAY_6      30000 non-null  int64
 9   BILL_AMT1  30000 non-null  int64
 10  BILL_AMT2  30000 non-null  int64
 11  BILL_AMT3  30000 non-null  int64
 12  BILL_AMT4  30000 non-null  int64
 13  BILL_AMT5  30000 non-null  int64
 14  BILL_AMT6  30000 non-null  int64
 15  PAY_AMT1   30000 non-null  int64
 16  PAY_AMT2   30000 non-null  int64
 17  PAY_AMT3   30000 non-null  int64
 18  PAY_AMT4   30000 non-null  int64
 19  PAY_AMT5   30000 non-null  int64
 20  PAY_AMT6   30000 non-null  int64
 21  DEFAULT    30000 non-null  int64
dtypes: int64(22)
memory usage: 5.0 MB

In [62]:
# Finding duplicate in the datasets
print('Sum of duplicate rows : ',df.duplicated().sum())

Sum of duplicate rows :  75

In [63]:
# Removing duplicate rows
df = df.drop_duplicates()
print('Updated Rows*Columns : ', df.shape)

Updated Rows*Columns :  (29925, 22)

In [64]:
print("Sum of Null value in for every columns : \n", df.isnull().sum())

Sum of Null value in for every columns :
 LIMIT_BAL    0
EDUCATION    0
AGE          0
PAY_0        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [65]:
df.info()

<class 'pandas.DataFrame'>
Index: 29925 entries, 0 to 29999
Data columns (total 22 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  29925 non-null  int64
 1   EDUCATION  29925 non-null  int64
 2   AGE        29925 non-null  int64
 3   PAY_0      29925 non-null  int64
 4   PAY_2      29925 non-null  int64
 5   PAY_3      29925 non-null  int64
 6   PAY_4      29925 non-null  int64
 7   PAY_5      29925 non-null  int64
 8   PAY_6      29925 non-null  int64
 9   BILL_AMT1  29925 non-null  int64
 10  BILL_AMT2  29925 non-null  int64
 11  BILL_AMT3  29925 non-null  int64
 12  BILL_AMT4  29925 non-null  int64
 13  BILL_AMT5  29925 non-null  int64
 14  BILL_AMT6  29925 non-null  int64
 15  PAY_AMT1   29925 non-null  int64
 16  PAY_AMT2   29925 non-null  int64
 17  PAY_AMT3   29925 non-null  int64
 18  PAY_AMT4   29925 non-null  int64
 19  PAY_AMT5   29925 non-null  int64
 20  PAY_AMT6   29925 non-null  int64
 21  DEFAULT    29925 non-null  int64
dtypes: int64(22)
memory usage: 5.3 MB

In [66]:
df.head()

,LIMIT_BAL,EDUCATION,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,PAY_6,BILL_AMT1,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000,2,24,2,2,-1,-1,-2,-2,3913,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,26,-1,2,0,0,0,2,2682,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,34,0,0,0,0,0,0,29239,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,37,0,0,0,0,0,0,46990,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,2,57,-1,0,-1,0,0,0,8617,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [67]:
# so in the UCI Machine learning they explicitly mention the education are only in between 0,1,2 and 4
# So to avoid any miss-happens we are making 0,5,6,7,8.--> 4
df['EDUCATION'] = df['EDUCATION'].replace({0: 4, 5:4, 6:4})

# verifying 
print(df['EDUCATION'].value_counts().sort_index())

EDUCATION
1    10532
2    14011
3     4914
4      468
Name: count, dtype: int64

In [68]:
# Check what happened
print(df['EDUCATION'].value_counts())
print(df['EDUCATION'].isnull().sum())

EDUCATION
2    14011
1    10532
3     4914
4      468
Name: count, dtype: int64
0

In [75]:
print(df.columns.tolist())

['LIMIT_BAL', 'EDUCATION', 'AGE', 'PAY_0', 'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6', 'DEFAULT ']

In [69]:
# for PAY columns only valid values are 
for col in ['PAY_0', 'PAY_2','PAY_3','PAY_4','PAY_5','PAY_6']:
    print(col, df[col].unique())
# in UCI they explicitly mention -1=pay_duly, =1, 1 month delay...2 for 2 month...so on til 9

PAY_0 [ 2 -1  0 -2  1  3  4  8  7  5  6]
PAY_2 [ 2  0 -1 -2  3  5  7  4  1  6  8]
PAY_3 [-1  0  2 -2  3  4  6  7  1  5  8]
PAY_4 [-1  0 -2  2  3  4  5  7  6  1  8]
PAY_5 [-2  0 -1  2  3  5  4  7  8  6]
PAY_6 [-2  2  0 -1  3  6  4  7  8  5]

In [70]:
pay_cols = ['PAY_0','PAY_2','PAY_3','PAY_4','PAY_5','PAY_6']
df[pay_cols] = df[pay_cols].replace({-2: -1, 0:-1})
# here we replce -2 with -1 and 0 with -1

In [71]:
for col in ['BILL_AMT1', 'BILL_AMT2','BILL_AMT3','BILL_AMT4', 'BILL_AMT5','BILL_AMT6']:
    print(col, 'Min:', df[col].min(), 'Max:', df[col].max())
# so here the are allow cause the credit balance are overpaid

BILL_AMT1 Min: -165580 Max: 964511
BILL_AMT2 Min: -69777 Max: 983931
BILL_AMT3 Min: -157264 Max: 1664089
BILL_AMT4 Min: -170000 Max: 891586
BILL_AMT5 Min: -81334 Max: 927171
BILL_AMT6 Min: -339603 Max: 961664

In [72]:
for col in ['PAY_AMT1','PAY_AMT2','PAY_AMT3',
            'PAY_AMT4','PAY_AMT5','PAY_AMT6']:
    print(col, 'Min:', df[col].min(), 'Max:', df[col].max())
    # so there's no negative value so it's already clean

PAY_AMT1 Min: 0 Max: 873552
PAY_AMT2 Min: 0 Max: 1684259
PAY_AMT3 Min: 0 Max: 896040
PAY_AMT4 Min: 0 Max: 621000
PAY_AMT5 Min: 0 Max: 426529
PAY_AMT6 Min: 0 Max: 528666

In [73]:
for col in ['PAY_AMT1','PAY_AMT2','PAY_AMT3',
            'PAY_AMT4','PAY_AMT5','PAY_AMT6']:
    print(col, 'Min:', df[col].min(), 'Max:', df[col].max())

PAY_AMT1 Min: 0 Max: 873552
PAY_AMT2 Min: 0 Max: 1684259
PAY_AMT3 Min: 0 Max: 896040
PAY_AMT4 Min: 0 Max: 621000
PAY_AMT5 Min: 0 Max: 426529
PAY_AMT6 Min: 0 Max: 528666

In [79]:
cat_cols = ['EDUCATION', 'PAY_0', 'PAY_2', 'PAY_3', 
            'PAY_4', 'PAY_5', 'PAY_6', 'DEFAULT']

df[cat_cols] = df[cat_cols].astype('category')

In [76]:
df = df.rename(columns={'DEFAULT ':'DEFAULT'})

In [78]:
df.columns.tolist()

['LIMIT_BAL',
 'EDUCATION',
 'AGE',
 'PAY_0',
 'PAY_2',
 'PAY_3',
 'PAY_4',
 'PAY_5',
 'PAY_6',
 'BILL_AMT1',
 'BILL_AMT2',
 'BILL_AMT3',
 'BILL_AMT4',
 'BILL_AMT5',
 'BILL_AMT6',
 'PAY_AMT1',
 'PAY_AMT2',
 'PAY_AMT3',
 'PAY_AMT4',
 'PAY_AMT5',
 'PAY_AMT6',
 'DEFAULT']

In [82]:
df.info()

<class 'pandas.DataFrame'>
Index: 29925 entries, 0 to 29999
Data columns (total 22 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   LIMIT_BAL  29925 non-null  int64
 1   EDUCATION  29925 non-null  category
 2   AGE        29925 non-null  int64
 3   PAY_0      29925 non-null  category
 4   PAY_2      29925 non-null  category
 5   PAY_3      29925 non-null  category
 6   PAY_4      29925 non-null  category
 7   PAY_5      29925 non-null  category
 8   PAY_6      29925 non-null  category
 9   BILL_AMT1  29925 non-null  int64
 10  BILL_AMT2  29925 non-null  int64
 11  BILL_AMT3  29925 non-null  int64
 12  BILL_AMT4  29925 non-null  int64
 13  BILL_AMT5  29925 non-null  int64
 14  BILL_AMT6  29925 non-null  int64
 15  PAY_AMT1   29925 non-null  int64
 16  PAY_AMT2   29925 non-null  int64
 17  PAY_AMT3   29925 non-null  int64
 18  PAY_AMT4   29925 non-null  int64
 19  PAY_AMT5   29925 non-null  int64
 20  PAY_AMT6   29925 non-null  int64
 21  DEFAULT    29925 non-null  category
dtypes: category(8), int64(14)
memory usage: 3.7 MB

In [83]:
df.to_csv('Cleaned_datasets.csv', index=False)